### ISSUE TITLE
@sphuber Do you want to join in maintaining this recipe?

### ISSUE THREAD

**Issue by jan-janssen** [conda-forge/aiida-shell-feedstock#3]
### Comment:

@sphuber I created this conda recipe as part of the collaboration with @mbercx and @GeigerJ2 on  https://github.com/materialdigital/ADIS2023 . Still it would be great to have somebody from @conda-forge/aiida-core to join on maintaining this recipe as well.

**Comment by sphuber** [comment]
Sure, you can add me as maintainer

**Comment by jan-janssen** [comment]
Done
